name: fun-ts build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: "pnpm"

      - run: pnpm ci
      - run: pnpm run build --if-present
      - run: pnpm run check --if-present
      - run: pnpm run test --if-present
