name: fetch release

on:
    release:
        types: [created]

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.14.0
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: npm run check-fetch
            - run: npm run test-fetch
            - run: npm run publish-fetch
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
