name: publish packages

on:
    push:
        tags:
            - "v*"

jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 16.14.2
                  registry-url: "https://registry.npmjs.org"
            - run: npm ci
            - run: npm run build
            - run: npm run check
            - run: npm run test
            - run: npm run deliver
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
