name: publish packages

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: install pnpm
        run: npm i -g pnpm@7.29.1

      - run: pnpm i
      - run: pnpm run build
      - run: pnpm run check
      - run: pnpm run test
      - run: pnpm run deliver
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
